name: check-code-style

on:
    pull_request:
        branches: [master, dev]
    push:
        branches: [dev]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"
                  cache: "pip"
            - uses: pre-commit/action@v2.0.3
